export const books = [
  {
    id: "1",
    name: "The Great Gatsby",
    image: "/images/gatsby.jpg",
    description: "A novel written by American author F. Scott Fitzgerald.",
    author: "F. Scott Fitzgerald",
    category: "Fiction",
    price: 10.99,
    countInStock: 15,
    rating: 4.7,
    numReviews: 1250,
  },
  {
    id: "2",
    name: "To Kill a Mockingbird",
    image: "/images/mockingbird.jpg",
    description: "A novel by Harper Lee published in 1960.",
    author: "Harper Lee",
    category: "Fiction",
    price: 7.99,
    countInStock: 20,
    rating: 4.8,
    numReviews: 2350,
  },
  {
    id: "3",
    name: "1984",
    image: "/images/1984.jpg",
    description: "A dystopian social science fiction novel by George Orwell.",
    author: "George Orwell",
    category: "Science Fiction",
    price: 8.99,
    countInStock: 30,
    rating: 4.6,
    numReviews: 1825,
  },
  {
    id: "4",
    name: "Pride and Prejudice",
    image: "/images/pride.jpg",
    description: "A romantic novel by Jane Austen, published in 1813.",
    author: "Jane Austen",
    category: "Romance",
    price: 6.99,
    countInStock: 12,
    rating: 4.9,
    numReviews: 2500,
  },
  {
    id: "5",
    name: "The Hobbit",
    image: "/images/hobbit.jpg",
    description: "A children's fantasy novel by J. R. R. Tolkien.",
    author: "J. R. R. Tolkien",
    category: "Fantasy",
    price: 9.99,
    countInStock: 18,
    rating: 4.7,
    numReviews: 2100,
  },
  {
    id: "6",
    name: "Moby-Dick",
    image: "/images/mobydick.jpg",
    description: "A novel by Herman Melville, published in 1851.",
    author: "Herman Melville",
    category: "Adventure",
    price: 11.99,
    countInStock: 8,
    rating: 4.3,
    numReviews: 890,
  },
  {
    id: "7",
    name: "War and Peace",
    image: "/images/warandpeace.jpg",
    description: "A novel by Leo Tolstoy, first published from 1865 to 1869.",
    author: "Leo Tolstoy",
    category: "Historical Fiction",
    price: 12.99,
    countInStock: 5,
    rating: 4.8,
    numReviews: 980,
  },
];
