import bookgeorge from "@assets/images/book-george.jpg";
import gatsby from "@assets/images/gatsby.jpg";
import hobbit from "@assets/images/hobbit.jpg";
import mobydick from "@assets/images/mobydick.jpg";
import mockingbird from "@assets/images/mockingbird.jpg";
import pride from "@assets/images/pride.webp";
import warandpeace from "@assets/images/warandpeace.jpg";

export const books = [
  {
    id: "0",
    title: "The Great Gatsby",
    image: gatsby.src,
    description: "A novel written by American author F. Scott Fitzgerald.",
    author: "F. Scott Fitzgerald",
    category: "Fiction",
    price: 10.99,
    count_in_stock: 15,
    rating: 4.7,
    num_reviews: 1250,
  },
  {
    id: "1",
    title: "To Kill a Mockingbird",
    image: mockingbird.src,
    description: "A novel by Harper Lee published in 1960.",
    author: "Harper Lee",
    category: "Fiction",
    price: 7.99,
    count_in_stock: 20,
    rating: 4.8,
    num_reviews: 2350,
  },
  {
    id: "2",
    title: "1984",
    image: bookgeorge.src,
    description: "A dystopian social science fiction novel by George Orwell.",
    author: "George Orwell",
    category: "Science Fiction",
    price: 8.99,
    count_in_stock: 30,
    rating: 3.6,
    num_reviews: 1825,
  },
  {
    id: "3",
    title: "Pride and Prejudice",
    image: pride.src,
    description: "A romantic novel by Jane Austen, published in 1813.",
    author: "Jane Austen",
    category: "Romance",
    price: 6.99,
    count_in_stock: 12,
    rating: 4.9,
    num_reviews: 2500,
  },
  {
    id: "4",
    title: "The Hobbit",
    image: hobbit.src,
    description: "A children's fantasy novel by J. R. R. Tolkien.",
    author: "J. R. R. Tolkien",
    category: "Fantasy",
    price: 9.99,
    count_in_stock: 18,
    rating: 4,
    num_reviews: 2100,
  },
  {
    id: "5",
    title: "Moby-Dick",
    image: mobydick.src,
    description: "A novel by Herman Melville, published in 1851.",
    author: "Herman Melville",
    category: "Adventure",
    price: 11.99,
    count_in_stock: 8,
    rating: 4.3,
    num_reviews: 890,
  },
  {
    id: "6",
    title: "War and Peace",
    image: warandpeace.src,
    description: "A novel by Leo Tolstoy, first published from 1865 to 1869.",
    author: "Leo Tolstoy",
    category: "Historical Fiction",
    price: 12.99,
    count_in_stock: 5,
    rating: 4.8,
    num_reviews: 980,
  },
];
